import React from 'react';

const ReportExporter = ({ data, location, alerts }) => {
  const generateCSV = () => {
    if (!data || data.length === 0) return;
    
    const headers = ['Timestamp', 'Location', 'Vegetation Index', 'Erosion Index', 'Moisture Level'];
    const csvContent = [
      headers.join(','),
      ...data.map(row => [
        row.timestamp,
        row.location,
        row.vegetation_index,
        row.erosion_index,
        row.moisture_level
      ].join(','))
    ].join('\n');
    
    downloadFile(csvContent, `soil-health-${location}-${new Date().toISOString().split('T')[0]}.csv`, 'text/csv');
  };

  const generateReport = () => {
    if (!data || data.length === 0) return;
    
    const latest = data[0];
    const reportContent = `
LAND REGEN SOIL HEALTH REPORT
=============================

Location: ${location}
Report Date: ${new Date().toLocaleString()}
Data Points: ${data.length}

CURRENT STATUS
--------------
Vegetation Index: ${latest.vegetation_index.toFixed(2)}
Erosion Index: ${latest.erosion_index.toFixed(2)}
Moisture Level: ${latest.moisture_level.toFixed(1)}%

ALERTS
------
${alerts.length > 0 ? alerts.map(alert => `- ${alert.message}`).join('\n') : 'No active alerts'}

RECOMMENDATIONS
---------------
${latest.erosion_index > 0.75 ? '- Implement erosion control measures\n' : ''}${latest.vegetation_index < 0.4 ? '- Deploy vegetation restoration program\n' : ''}${latest.moisture_level < 35 ? '- Apply mulch or irrigation support\n' : ''}${latest.erosion_index <= 0.75 && latest.vegetation_index >= 0.4 && latest.moisture_level >= 35 ? '- Continue current management practices\n' : ''}
Generated by Land ReGen Dashboard
    `.trim();
    
    downloadFile(reportContent, `soil-health-report-${location}-${new Date().toISOString().split('T')[0]}.txt`, 'text/plain');
  };

  const downloadFile = (content, filename, contentType) => {
    const blob = new Blob([content], { type: contentType });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = filename;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="report-exporter">
      <h3>📊 Export & Reports</h3>
      
      <div className="export-buttons">
        <button className="export-btn csv" onClick={generateCSV}>
          📄 Export CSV Data
        </button>
        
        <button className="export-btn report" onClick={generateReport}>
          📋 Generate Report
        </button>
        
        <button 
          className="export-btn email"
          onClick={() => {
            const subject = `Soil Health Report - ${location}`;
            const body = `Please find the soil health data for ${location}. Current status: Vegetation ${data[0]?.vegetation_index.toFixed(2)}, Erosion ${data[0]?.erosion_index.toFixed(2)}, Moisture ${data[0]?.moisture_level.toFixed(1)}%`;
            window.open(`mailto:?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`);
          }}
        >
          📧 Email Report
        </button>
      </div>
      
      <div className="export-info">
        <p>📈 Data includes {data?.length || 0} readings from {location}</p>
        <p>⚠️ {alerts?.length || 0} active alerts included in reports</p>
      </div>
    </div>
  );
};

export default ReportExporter;